name: Publish Release on Tag Push

on:
  push:
    branches: master
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Print Thing
        if: startsWith(github.ref, 'refs/tags/')
        # uses: actions/create-release@v1
        # id: create_release
        # with:
        #   draft: false
        #   prerelease: false
        #   release_name: ${{ github.ref }}
        #   tag_name: ${{ github.ref }}
        #   body_path: CHANGELOG.md
        run: 'echo "Hello World"'
